#!/usr/bin/env bash

if
  [[ -s "/home/cwj/.rvm/gems/ruby-2.2.2@global/environment" ]]
then
  source "/home/cwj/.rvm/gems/ruby-2.2.2@global/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/cwj/.rvm/gems/ruby-2.2.2@global/environment'" >&2
  exit 1
fi
