# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1431437291);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1431439204);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1431444131);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1431437171);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1431437051);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 286720);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150125222326");
user_pref("browser.slowStartup.averageTime", 1633);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150125222326");
user_pref("browser.startup.homepage_override.mstone", "35.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button-throttled\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":3,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1431436874651");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1431436877320");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1431523277320");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1430817503403");
user_pref("datareporting.policy.firstRunTime", "1430815688227");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1425);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 1705);
user_pref("datareporting.sessions.current.startTime", "1431446397123");
user_pref("datareporting.sessions.current.totalTime", 24);
user_pref("datareporting.sessions.currentIndex", 24);
user_pref("datareporting.sessions.previous.10", "{\"s\":1431437495773,\"a\":4,\"t\":24,\"c\":true,\"m\":513,\"fp\":1947,\"sr\":2176}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1431437532638,\"a\":6,\"t\":40,\"c\":true,\"m\":33,\"fp\":1329,\"sr\":1667}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1431437884662,\"a\":3,\"t\":16,\"c\":true,\"m\":33,\"fp\":1449,\"sr\":1676}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1431439083272,\"a\":26,\"t\":620,\"c\":true,\"m\":35,\"fp\":1485,\"sr\":1837}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1431439947872,\"a\":62,\"t\":2185,\"c\":true,\"m\":36,\"fp\":1322,\"sr\":1655}");
user_pref("datareporting.sessions.previous.15", "{\"s\":1431442136077,\"a\":8,\"t\":39,\"c\":true,\"m\":142,\"fp\":1471,\"sr\":1791}");
user_pref("datareporting.sessions.previous.16", "{\"s\":1431442353887,\"a\":1,\"t\":6,\"c\":true,\"m\":41,\"fp\":1346,\"sr\":1684}");
user_pref("datareporting.sessions.previous.17", "{\"s\":1431442368763,\"a\":7,\"t\":114,\"c\":true,\"m\":40,\"fp\":1822,\"sr\":1779}");
user_pref("datareporting.sessions.previous.18", "{\"s\":1431442533514,\"a\":6,\"t\":27,\"c\":true,\"m\":33,\"fp\":1327,\"sr\":1623}");
user_pref("datareporting.sessions.previous.19", "{\"s\":1431442751679,\"a\":2,\"t\":7,\"c\":true,\"m\":32,\"fp\":1763,\"sr\":1721}");
user_pref("datareporting.sessions.previous.20", "{\"s\":1431442773208,\"a\":9,\"t\":59,\"c\":true,\"m\":41,\"fp\":1920,\"sr\":1869}");
user_pref("datareporting.sessions.previous.21", "{\"s\":1431442938242,\"a\":2,\"t\":9,\"c\":true,\"m\":33,\"fp\":1498,\"sr\":1699}");
user_pref("datareporting.sessions.previous.22", "{\"s\":1431443020952,\"a\":57,\"t\":2215,\"c\":true,\"m\":35,\"fp\":1714,\"sr\":1947}");
user_pref("datareporting.sessions.previous.23", "{\"s\":1431446216868,\"a\":3,\"t\":13,\"c\":true,\"m\":35,\"fp\":1370,\"sr\":1701}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1431436809261,\"a\":15,\"t\":498,\"c\":true,\"m\":586,\"fp\":3018,\"sr\":3368}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1431437427216,\"a\":9,\"t\":43,\"c\":true,\"m\":41,\"fp\":1387,\"sr\":1689}");
user_pref("datareporting.sessions.prunedIndex", 7);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.08.06.beta,ubufox%40ubuntu.com:3.0,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1431437292);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150402.01");
user_pref("extensions.lastAppVersion", "35.0.1");
user_pref("extensions.lastPlatformVersion", "35.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-ko@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-ko@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"37.0.2\",\"st\":1429295623000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"37.0.2\",\"st\":1429295568000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0.1\",\"st\":1424288976000,\"mt\":1422226198000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"37.0.2\",\"st\":1429295568000}},\"app-system-share\":{\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.08.06.beta\",\"st\":1424289188000,\"mt\":1407283796000},\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1424289188000,\"mt\":1420839872000},\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1424289189000,\"mt\":1397665356000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1424289189000,\"mt\":1390969638000}}}");
user_pref("gecko.buildID", "20150125222326");
user_pref("gecko.mstone", "35.0.1");
user_pref("idle.lastDailyNotification", 1431437060);
user_pref("loop.soft_start_ticket_number", 12680815);
user_pref("loop.throttled2", false);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1430817505);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1431436873);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.atsvc.enabled", false);
user_pref("network.http.atsvc.oe", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1431436875);
user_pref("places.history.expiration.transient_current_max_pages", 26309);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1430819525);
user_pref("toolkit.startup.last_success", 1431446397);
user_pref("toolkit.telemetry.previousBuildID", "20150125222326");
